### ISSUE TITLE
File import doesn't support non-ASCII content

### ISSUE THREAD

**Issue by vordan** [tableflowhq/csv-import#211]
When I attempt to import a UTF-8 encoded CSV file containing non-ASCII characters (such as Cyrillic), the characters are not decoded correctly. I'm uncertain where the issue lies - with the parser or the record list, but the result is garbled text.

I am also including the CSV file itself.
[banki-makedonija.csv](https://github.com/tableflowhq/csv-import/files/14486711/banki-makedonija.csv)

![image](https://github.com/tableflowhq/csv-import/assets/50054/e4b7caf2-75fa-4144-b665-e14a07c8d272)

**Comment by ciminelli** [comment]
Thanks for the issue @vordan, we'll have a fix out soon!

**Comment by ciminelli** [comment]
@vordan this is fixed in version `1.0.9`
