### ISSUE TITLE
Error: Unsupported ZIP Compression method NaN

### ISSUE THREAD

**Issue by iwdwebman** [tableflowhq/csv-import#216]
Using NextJS and trying to upload XLXS files and I get the error: Error: Unsupported ZIP Compression method NaN. I can use the XLSX library direct without issue. Also CSV files work just fine. I tried using the component normally and through dynamic load.

`const DynamicImporter = dynamic(
  () => import("csv-import-react").then((mod) => mod.CSVImporter),
  {
    loading: () => <p>Loading...</p>,
    ssr: false,
  }
);`

`              <>
                <DynamicImporter
                  modalIsOpen={isUploaderOpen}
                  modalOnCloseTriggered={() => setIsUploaderOpen(false)}
                  onComplete={(data) => console.log(data)}
                  template={{
                    columns: [
                      {
                        name: "First Name",
                        key: "first_name",
                        required: true,
                        description: "The first name of the user",
                        suggested_mappings: ["First", "Name", "firstname"],
                      },
                      {
                        name: "Phone",
                        data_type: "phone",
                        suggested_mappings: ["Phone", "telephone", "tel"],
                      },
                    ],
                  }}
                  waitOnComplete={true}
                  skipHeaderRowSelection={true}
                />
                <Button type="primary" onClick={() => setIsUploaderOpen(true)}>
                  <Icon icon="upload" className={clsx("mr-2")} />
                  Upload Contacs
                </Button>
              </>`

I am not sure how the XLSX library is in use here but seems to be thinking its a zip file.

**Comment by ciminelli** [comment]
Hey @iwdwebman, thanks for the issue; we're looking into this now.

**Comment by ciminelli** [comment]
@iwdwebman this is fixed in version `1.0.10`, thanks again for the report!
