### ISSUE TITLE
NextJS document fix for clearCache

### ISSUE THREAD

**Issue by robertalv** [tableflowhq/csv-import#225]
⨯ node_modules/csv-import-react/build/index.esm.js (45883:0) @ createCache
 ⨯ ReferenceError: document is not defined

```
{
  if (typeof window !== 'undefined') {
    container = options.container || document.head;
    Array.prototype.forEach.call(
      document.querySelectorAll("style[data-emotion^=\"" + key + " \"]"), 
      function (node) {
        var attrib = node.getAttribute("data-emotion").split(' ');

        for (var i = 1; i < attrib.length; i++) {
          inserted[attrib[i]] = true;
        }

        nodesToHydrate.push(node);
      }
    );
  }
}
```

**Comment by 7laria** [comment]
Hi @robertalv ! I tried this fix but is still not working properly.
Next.js: v14.2.5
Here the sample component: `export default function Home() {
    const [isOpen, setIsOpen] = useState(true);
    return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <CSVImporter
                modalIsOpen={isOpen}
                modalOnCloseTriggered={() => setIsOpen(false)}
                darkMode={false}
                onComplete={(data) => console.log(data)}
                template={{
                    columns: [
                        {
                            name: "name",
                            key: "name",
                            required: true,
                            description: "name",
                            suggested_mappings: ["name"],
                        },
                        
                    ],
                }}
            />
        </main>
    );
}`

and the error related: `ReferenceError: document is not defined`

**Comment by yoavz** [comment]
if anyone lands here, I used this to workaround: 

```
const CSVImporter = dynamic(
  () => import('csv-import-react').then((mod) => mod.CSVImporter),
  {
    ssr: false,
  },
);
```
