### ISSUE TITLE
Locale feature / can I translate the lib?

### ISSUE THREAD

**Issue by gabrielwiggert** [tableflowhq/csv-import#236]
Hey! First of all, thanks and great work with the importer.

My issue is that I'm using it for a portuguese speaking audience. Before a locale feature is implemented, how could I go about translating the lib's frontend?

Also, I volunteer for translating it to portuguese if the locale feature is ever implemented ;)

Cheers!

**Comment by ciminelli** [comment]
This is now available with version `1.0.12`.

The documentation can be found here: https://github.com/tableflowhq/csv-import?tab=readme-ov-file#internationalization

You can use the `customTranslations` prop to add your own translations for Portuguese, and if you want to submit a PR for translating into Portuguese, you would just need to add the translation file (see `src/i18n/es.ts` as an example). Appreciate it!
