### ISSUE TITLE
i18n, support internationalization

### ISSUE THREAD

**Issue by nsb** [tableflowhq/csv-import#84]
It would be great if we could specify translated strings for the embedded importer.

**Comment by pintaf** [comment]
I'm using this library, I need to add support for french.
What do you think is the best approach?

1️⃣ configuring other languages as an option of createCSVImporter
Pros: No need to add a i18n library or having to handle PR for every new language supported
Cons: more complex use

2️⃣ handling different languages inside the component 
Pros: could display automatically the text in the correct language depending on the browser language or could be overriden. More "Plug & Play"
Cons: having to handle different languages, etc. But could be simplified by the use of systems like crowdin.

**Comment by pintaf** [comment]
looks great !

**Comment by ciminelli** [comment]
This is now available with version `1.0.12`! Thanks to @civan for his work on this.

The documentation can be found here: https://github.com/tableflowhq/csv-import?tab=readme-ov-file#internationalization
